// Objective-C API for talking to github.com/jagentdesk/jagentdesk-tailscale Go package.
//   gobind -lang=objc github.com/jagentdesk/jagentdesk-tailscale
//
// File is generated by gobind. Do not edit.

#ifndef __Tailscalebridge_H__
#define __Tailscalebridge_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class TailscalebridgeBridge;

/**
 * Bridge is the mobile transport primitive. It owns an embedded tsnet node
and exposes a loopback TCP forwarder. The JavaScript WebSocket client can
connect to the loopback endpoint while the bridge dials the daemon through
Tailscale; no relay server or OS-level Tailscale process is involved.
 */
@interface TailscalebridgeBridge : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSString* _Nonnull)devicePublicKeyB64;
- (NSString* _Nonnull)localAddress;
- (BOOL)proxy:(NSString* _Nullable)target error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)signNonce:(NSString* _Nullable)nonce;
- (BOOL)start:(NSString* _Nullable)authKey stateDir:(NSString* _Nullable)stateDir hostname:(NSString* _Nullable)hostname target:(NSString* _Nullable)target error:(NSError* _Nullable* _Nullable)error;
- (BOOL)stop:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)tailnetName;
@end

#endif
