name = "jagentdesk-website"
account_id = "10ed39a1dbf316e30abd0c409bed40d6"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = "./src/server-entry.ts"

[observability]
enabled = true
