
// Objective-C API for talking to the following Go packages
//
//	github.com/jagentdesk/jagentdesk-tailscale
//
// File is generated by gomobile bind. Do not edit.
#ifndef __TailscaleBridgeNative_FRAMEWORK_H__
#define __TailscaleBridgeNative_FRAMEWORK_H__

#include "Tailscalebridge.objc.h"
#include "Universe.objc.h"

#endif
