package tailscalebridge

import (
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"tailscale.com/tsnet"
)

// Bridge is the mobile transport primitive. It owns an embedded tsnet node
// and exposes a loopback TCP forwarder. The JavaScript WebSocket client can
// connect to the loopback endpoint while the bridge dials the daemon through
// Tailscale; no relay server or OS-level Tailscale process is involved.
type Bridge struct {
	mu          sync.Mutex
	authMu      sync.RWMutex
	server      *tsnet.Server
	listener    net.Listener
	closed      chan struct{}
	tailnetName string
	authURL     string
	deviceKey   ed25519.PrivateKey
}

func (b *Bridge) LocalAddress() string {
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.listener == nil {
		return ""
	}
	return b.listener.Addr().String()
}

func (b *Bridge) TailnetName() string {
	b.mu.Lock()
	server := b.server
	b.mu.Unlock()
	if server != nil {
		if client, err := server.LocalClient(); err == nil {
			ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
			status, statusErr := client.Status(ctx)
			cancel()
			if statusErr == nil && status.BackendState == "Running" && status.Self != nil {
				b.setTailnetName(strings.TrimSuffix(status.Self.DNSName, "."))
			}
		}
	}
	return b.getTailnetName()
}

// AuthURL returns the node-specific Tailscale authorization URL generated by
// tsnet.Start when this embedded node has not been authenticated yet.
func (b *Bridge) AuthURL() string {
	if cached := b.getAuthURL(); cached != "" {
		return cached
	}
	b.mu.Lock()
	server := b.server
	b.mu.Unlock()
	if server != nil {
		if client, err := server.LocalClient(); err == nil {
			ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
			status, statusErr := client.Status(ctx)
			cancel()
			if statusErr == nil {
				b.setAuthURL(status.AuthURL)
				if status.BackendState == "Running" && status.Self != nil {
					b.setTailnetName(strings.TrimSuffix(status.Self.DNSName, "."))
				}
			}
		}
	}
	return b.getAuthURL()
}

func (b *Bridge) setAuthURL(value string) {
	b.authMu.Lock()
	b.authURL = value
	b.authMu.Unlock()
}

func (b *Bridge) getAuthURL() string {
	b.authMu.RLock()
	defer b.authMu.RUnlock()
	return b.authURL
}

func (b *Bridge) setTailnetName(value string) {
	b.authMu.Lock()
	b.tailnetName = value
	b.authMu.Unlock()
}

func (b *Bridge) getTailnetName() string {
	b.authMu.RLock()
	defer b.authMu.RUnlock()
	return b.tailnetName
}

func (b *Bridge) Start(authKey, stateDir, hostname, target string) error {
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.server != nil {
		// getStatus() may have started an unauthenticated tsnet node in order to
		// obtain an interactive login URL. An auth-key submission must replace
		// that node; returning here would report success while keeping the node
		// unauthenticated.
		if strings.TrimSpace(authKey) == "" || b.getTailnetName() != "" {
			return nil
		}
		close(b.closed)
		if b.listener != nil {
			_ = b.listener.Close()
		}
		_ = b.server.Close()
		b.listener, b.server = nil, nil
		b.setTailnetName("")
		b.setAuthURL("")
	}

	srv := &tsnet.Server{
		AuthKey:  authKey,
		Dir:      stateDir,
		Hostname: hostname,
		Logf: func(format string, args ...any) {
			// Keep enough native diagnostics to explain a failed mobile login,
			// while redacting the one-time browser URL from device logs.
			message := redactTailscaleLog(fmt.Sprintf(format, args...))
			if strings.Contains(message, "control:") || strings.Contains(message, "RegisterReq") || strings.Contains(message, "TryLogin") || strings.Contains(message, "error") || strings.Contains(message, "failed") {
				fmt.Printf("[JAgentDeskTailscale] %s\\n", message)
			}
		},
		UserLogf: func(format string, args ...any) {
			message := fmt.Sprintf(format, args...)
			if index := strings.Index(message, "https://login.tailscale.com/"); index >= 0 {
				b.setAuthURL(strings.Fields(message[index:])[0])
			}
			fmt.Printf("[JAgentDeskTailscale] %s\\n", redactTailscaleLog(message))
		},
	}
	fmt.Printf("[JAgentDeskTailscale] start begin interactive=%t\\n", strings.TrimSpace(authKey) == "")
	if strings.TrimSpace(authKey) == "" {
		if err := srv.Start(); err != nil {
			return fmt.Errorf("tailscale start: %w", err)
		}
	} else {
		upCtx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
		defer cancel()
		if _, err := srv.Up(upCtx); err != nil {
			return fmt.Errorf("tailscale up: %w", err)
		}
	}

	b.server, b.closed = srv, make(chan struct{})
	keyPath := filepath.Join(stateDir, "jagentdesk-device-ed25519.key")
	if key, err := os.ReadFile(keyPath); err == nil && len(key) == ed25519.PrivateKeySize {
		b.deviceKey = ed25519.PrivateKey(key)
	} else {
		publicKey, privateKey, err := ed25519.GenerateKey(rand.Reader)
		if err != nil {
			return fmt.Errorf("device key generation: %w", err)
		}
		if err := os.MkdirAll(stateDir, 0700); err != nil {
			return fmt.Errorf("device key directory: %w", err)
		}
		if err := os.WriteFile(keyPath, privateKey, 0600); err != nil {
			return fmt.Errorf("device key storage: %w", err)
		}
		_ = publicKey
		b.deviceKey = privateKey
	}
	if strings.TrimSpace(target) != "" {
		if err := b.startProxyLocked(target); err != nil {
			_ = srv.Close()
			return err
		}
	}

	name := ""
	if client, statusErr := srv.LocalClient(); statusErr == nil {
		statusCtx, statusCancel := context.WithTimeout(context.Background(), 10*time.Second)
		if status, err := client.Status(statusCtx); err == nil {
			b.setAuthURL(status.AuthURL)
			if status.BackendState == "Running" && status.Self != nil {
				name = strings.TrimSuffix(status.Self.DNSName, ".")
			}
		}
		statusCancel()
	}
	b.setTailnetName(name)
	if strings.TrimSpace(authKey) == "" {
		// Interactive login is asynchronous: the control plane can deliver the
		// node-specific URL after Start returns. The native adapter polls the
		// status with a bounded timeout and opens the URL in the system browser.
		fmt.Printf("[JAgentDeskTailscale] start returned interactive authURL=%t\\n", b.getAuthURL() != "")
		return nil
	}
	if b.getTailnetName() == "" {
		return fmt.Errorf("tailscale joined without a running tailnet")
	}
	return nil
}

func redactTailscaleLog(message string) string {
	if index := strings.Index(message, "https://login.tailscale.com/"); index >= 0 {
		prefix := message[:index]
		suffix := message[index:]
		if end := strings.IndexAny(suffix, " \\t\\r\\n\\\""); end >= 0 {
			return prefix + "<tailscale-login-url>" + suffix[end:]
		}
		return prefix + "<tailscale-login-url>"
	}
	return message
}

func (b *Bridge) DevicePublicKeyB64() string {
	b.mu.Lock()
	defer b.mu.Unlock()
	if len(b.deviceKey) != ed25519.PrivateKeySize {
		return ""
	}
	return base64.StdEncoding.EncodeToString(b.deviceKey.Public().(ed25519.PublicKey))
}

func (b *Bridge) SignNonce(nonce string) string {
	b.mu.Lock()
	defer b.mu.Unlock()
	if len(b.deviceKey) != ed25519.PrivateKeySize {
		return ""
	}
	return base64.StdEncoding.EncodeToString(ed25519.Sign(b.deviceKey, []byte(nonce)))
}

func (b *Bridge) Proxy(target string) error {
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.server == nil {
		return fmt.Errorf("tailscale is not started")
	}
	return b.startProxyLocked(target)
}

func (b *Bridge) startProxyLocked(target string) error {
	if strings.TrimSpace(target) == "" {
		return fmt.Errorf("tailscale target is required")
	}
	if b.listener != nil {
		return nil
	}
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return fmt.Errorf("loopback listen: %w", err)
	}
	b.listener = ln
	go b.acceptLoop(target)
	return nil
}

func (b *Bridge) acceptLoop(target string) {
	for {
		conn, err := b.listener.Accept()
		if err != nil {
			select {
			case <-b.closed:
				return
			default:
			}
			continue
		}
		go func() {
			remote, dialErr := b.server.Dial(context.Background(), "tcp", target)
			if dialErr != nil {
				_ = conn.Close()
				return
			}
			proxy(conn, remote)
		}()
	}
}

func (b *Bridge) Stop() error {
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.server == nil {
		return nil
	}
	close(b.closed)
	if b.listener != nil {
		_ = b.listener.Close()
	}
	if b.server != nil {
		_ = b.server.Close()
	}
	b.listener, b.server = nil, nil
	b.setTailnetName("")
	b.setAuthURL("")
	return nil
}
